<?php
/**
 * @var \Mageplaza\GiftCard\Block\History $block;
 */
$collection = $block->getTestCollection();
?>

<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('History')) ?></strong></div>
    <table class="data table" id="test-data-table">
        <caption class="table-caption">Vky Test Data</caption>
        <thead>
        <tr>
            <th scope="col" class="col title">Date</th>
            <th scope="col" class="col author">Code</th>
            <th scope="col" class="col content">Amount</th>
            <th scope="col" class="col actions">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($collection as $key => $data): ?>
            <tr>
                <td data-th="Date" class="col title"><?php echo $data->getAction_time(); ?></td>
                <td data-th="Code" class="col author"><?php echo $block->getCode($data); ?></td>
                <td data-th="Amount" class="col content"><?= $block->formatPrice($data->getAmount()) ?></td>
                <td data-th="Action" class="col created_at"><?php echo $data->getAction(); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>



