<form action="<?php echo $block->getActionUrl() ?>" method="post">
    <div class="form-group">
        <label for="code">Code</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nhap Code" name="code">

    </div>
    <div class="form-group">
        <label for="balance">Balance</label>
        <input type="number" class="form-control" id="exampleInputPassword1" placeholder="Balance" name="balance">
    </div>
    <div class="form-group">
        <label for="creatfrom">Create From</label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Create From" name="creatfrom">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
