<?php
/**
 * @var \Mageplaza\GiftCard\Block\TestView $block;
 */

$singleData = $block->getSingleData();

?>

<form action="<?php echo $block->getActionUrl().'id/'.$block->getRequest()->getParam('id'); ?>" method="post">
    <div class="form-group">
        <label for="code">Code</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nhap Code" name="code" value="<?php echo $singleData->getCode(); ?>">

    </div>
    <div class="form-group">
        <label for="balance">Balance</label>
        <input type="number" class="form-control" id="exampleInputPassword1" placeholder="Balance" name="balance" value = "<?php echo $singleData->getBalance(); ?>">
    </div>
    <div class="form-group">
        <label for="creatfrom">Create From</label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Create From" name="creatfrom" value ="<?php echo $singleData->getCreate_from(); ?>">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
